services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: